### ISSUE TITLE
Act_9 La nota informativa 

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-5-1#1]
Act_9 La nota informativa 
Equipo: Daisy Gonzalez Lita, Maribel Santiago Bautista, Ana Kimberly Hernández Pérez, Ariadna Monserrat López Aparicio.
[Nota informativa.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-5-1/files/9934766/Nota.informativa.pdf)

**Comment by ErikCuevas03** [comment]
El trabajo esta bien estructurado. Tiene como inicio lo fundamental: titulo, lugar y fecha donde se realizo , entrada,  cuerpo de la nota. Solo faltó agregar la portada con sus respectivos elementos.

Calificación 18

**Comment by josealfredo79** [comment]
Esta incompleta la nota

**Comment by josealfredo79** [comment]
Deben esforzarse mas por redactar mas parrafos para la nota informativa

**Comment by josealfredo79** [comment]
@ErikCuevas03 hay que evaluar objetivamente por favor...

**Comment by Daisy-GonzalezLita12** [comment]
Act_9 La nota informativa corregida
Equipo: Daisy Gonzalez Lita, Maribel Santiago Bautista, Ana Kimberly Hernández Pérez, Ariadna Monserrat López Aparicio.
[Nota informativa(CORRECCIÓN).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-5-1/files/9977673/Nota.informativa.CORRECCION.pdf)

**Comment by ErikCuevas03** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
